---
- hosts: all
  become: yes
  tasks:
    - name: install pip for python3
      apt:
        name: python3-pip
        state: present
        update_cache: yes
    - name: install newest pylxd module
      shell:
        cmd: "pip3 install pylxd"
    - name: prepare dir
      file:
        name: "/root/tools"
        state: directory
    - name: copy script
      copy:
        src: lxd_restore.py
        dest: /root/tools/lxd_restore.py
