Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.hostname = "LXDRestoreDev"
    config.vm.provider :virtualbox do |vb|
        vb.name = "lxd-restore-dev"
    end
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "provision_dev_environment.yml"
    end
end
